let num = [5, 8, 2, 9, 3]
num.push(1)
console.log(`Nosso vetor é ${num}`)
console.log(num)
var tamanho = num.length
console.log(`O vetor tem ${tamanho} posições`)
console.log(num[0])
console.log(`O primeiro valor do vetor é ${num[0]}`)

num.sort()
console.log("--- ORDENADO ---")
console.log(`Nosso vetor é ${num}`)
console.log(num)
console.log(`O vetor tem ${num.length} posições`)
console.log(num[0])
console.log(`O primeiro valor do vetor é ${num[0]}`)
var pos = num.indexOf(8)
console.log(`O valor 8 está na posição ${pos}`)
pos = num.indexOf(4)
console.log(`O valor 4 está na posição ${pos}`)